### PR TITLE
Unit and integration tests

### PR DESCRIPTION
**Pull request by tfrommen**
This (**not yet ready-for-merge**) pull request includes unit and integration tests as well as the necessary _infrastructure changes_ for them.

@reisraff please have a look at how I designed the tests. Feedback welcome.

Also, there are two things to discuss:

1. There is currently one **failing** test: `DistFileTest::testGetBasepath()` with the `incorrectlyMatchingRelativePath` data set. In my opinion, we cannot just do `str_replace()` in `DistFile::__comstruct()`, but have to make sure we **only replace at the beginning of the full path**, right? So I'd go ahead and change the constructor, which then will make the test pass.
1. For whatever reason, comparing `filemtime()` and the returned value of `DistFile::getLastChangeTime()` (which **is** `filemtime()` on the very same file I used) are not equal, but off by (in my case) one millisecond. I don't get it, that's why I (for now) changed if the one is greater than the other. Do you have any idea what's going on here? I tried using `clearstatcache()` here and there, and I already called `filemtime()` in the according data provider before. However, nothing changed, so I removed it again.

I will continue with the tests when I have time. Currently on vacation (but the weather sucks anyway).

### CODE REVIEW

**Comment by reisraff** [comment]
at first please, remove all binary in the `bin` directory just not the `phulp.php` and `phulp`.

Add to .gitignore:

```
/bin/*
!/bin/phulp.php
!/bin/phulp
```

**Comment by reisraff** [comment]
And the test will fail 'cause the correct data should be:

```
'incorrectlyMatchingRelativePath' => [
    'expected' => '/path',
    'fullpath' => '/path/to/directory' . DIRECTORY_SEPARATOR,
    'relativepath' => '/to/directory',
],
```

**Comment by reisraff** [comment]
One more thing, my output of phpunit:

```
PHPUnit 5.3.4 by Sebastian Bergmann and contributors.

................EE...                                             21 / 21 (100%)

Time: 76 ms, Memory: 6.00MB

There were 2 errors:

1) Phulp\Test\Unit\PipeIterateTest::testExecute with data set "noDistFiles" (array())
Only variables should be passed by reference

/home/reisraff/Projects/reisraff/phulp/src/PipeIterate.php:25
/home/reisraff/Projects/reisraff/phulp/test/Unit/PipeIterateTest.php:31

2) Phulp\Test\Unit\PipeIterateTest::testExecute with data set "withDistFiles" (array('/path/to/file.php', '/path/to/another/file.php', '/path/to/another/file.php'))
Only variables should be passed by reference

/home/reisraff/Projects/reisraff/phulp/src/PipeIterate.php:25
/home/reisraff/Projects/reisraff/phulp/test/Unit/PipeIterateTest.php:31

FAILURES!
Tests: 21, Assertions: 19, Errors: 2.
[phingcall] /home/reisraff/Projects/reisraff/phulp/build.xml:29:43: Task exited with code 2

BUILD FAILED
/home/reisraff/Projects/reisraff/phulp/build.xml:11:26: Execution of the target buildfile failed. Aborting.
Total time: 0.2390 seconds
```

The array_walk is returning a E_NOTICE. What we can do to fix it?

**Comment by reisraff** [comment]
About the `getLastChangeTime`, I need see with more affection.

**Comment by reisraff** [comment]
And about the conductor of DistFile if you get a way to get the basepath without doing str_replace go ahead with it.

**Comment by reisraff** [comment]
And add the `test` directory to `phplint` as a `fileset` in the `build.xml`

**Comment by reisraff** [comment]
And about the getLastChangeTime if you provide the `README.md` the test pass.

```
'thisFile' => [
    'expected' => filemtime(__DIR__ . '/../../README.md'),
    'name' => basename(__DIR__ . '/../../README.md'),
    'fullpath' => __DIR__ . DIRECTORY_SEPARATOR,
],
```

**Comment by reisraff** [comment]
And about the `getLastChangeTime` I guess is accepted 1 millisecond of inaccuracy.

**Comment by tfrommen** [comment]
In my opinion, [changes to the `.gitignore`](https://github.com/reisraff/phulp/pull/16#issuecomment-223256841) should be done in another branch (or directly in the master), and not in this PR. It could take some time for it to get merged anyway...

Your [proposed test data set](https://github.com/reisraff/phulp/pull/16#issuecomment-223258719) is not what I want to do/have in that particular test. I want to have something like `$fullpath = '/path/to/directory/'` and `$relativepath = '/to'` - in other words, `$relativepath` should be a substring **in the middle of `$fullpath`** (i.e., it should neither start at the beginning, nor end at the end of fullpath).
What the `$expected` return value should be, that's the real question, I guess. I'm not sure how fullpath and relativepath should be used here. But one should definitely either be the start or the end of the other, right? That's currently not the case, because we do a simple `str_replace()` which also matches/replaces somewhere in the middle - and that isn't correct, I think.
So, explain to me what fullpath and relativepath should be and how they are related to each other, then I take care of either [adapting the implementation](https://github.com/reisraff/phulp/pull/16#issuecomment-223270238), or the test - or both. :)

I already fixed the [errors](https://github.com/reisraff/phulp/pull/16#issuecomment-223258944) you mentioned locally, commit will follow soon.

For the [`build.xml`](https://github.com/reisraff/phulp/pull/16#issuecomment-223296478), I think it's the same as with `.gitignore`. Please do this in the master, or another (temporary). I also don't have any clue on phing. ;)

Of course, [1 msec difference](https://github.com/reisraff/phulp/pull/16#issuecomment-223301183) is no big deal - if one were to compare two distinct measurements. But in this case, I am reading a specific value of something that shouldn't have changed in any way. I will (try to) get to the bottom of that, because I'm not yet really satisifed with what the according test does rigt now.

**Comment by reisraff** [comment]
So when we are using SymfonyFinder we have the `realPath` and the `relativePath`. ***if I'm not mistaken***

The `realPath` is our `fullpath` without the file at end.
The `relativePath` is our `relativePath` also.

Explaning the `relativePath`

for example we have this scenario:

```
/project/
/project/dir1/
/project/dir1/dir2/file.php
```

if I pass for SymfonyFinder search in the `/project/dir1` the file `*.php` recursively. It should return for me:

```
[
    `Symfony-SplFileInfo` => [
        'realpath' => '/project/dir1/dir2/file.php',
        'relativepath' => '/dir2'
    ]
]
```

But in the Phulp furthermore I need the basepath that is the path passed to SymfonyFinder in this case the `/project/dir1`.

**Comment by reisraff** [comment]
I did some changes on master, please rebase this branch.

**Comment by tfrommen** [comment]
Closed in favor of #17.

**Pull request closed without merging**
